#!/bin/sh

export CGIT_REPOSITORIES_FILE="/tmp/cgit/github_repositories"
export GITHUB_USER=scanf
export CGIT_REPO_DIRECTORY=/tmp/cgit

mkdir -p $CGIT_REPO_DIRECTORY
touch $CGIT_REPOSITORIES_FILE


ruby run.rb
