#!/bin/sh

# This file is included in /etc/cgitrc
export CGIT_REPOSITORIES_FILE="/etc/github_repositories"
export GITHUB_USER=scanf
export CGIT_REPO_DIRECTORY=/srv/git

mkdir -p $CGIT_REPO_DIRECTORY
touch $CGIT_REPOSITORIES_FILE

ruby /root/src/github.com/scanf/github2cgit/run.rb
sudo chown -R www-data:www-data $CGIT_REPOSITORIES_FILE
